/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.uv.bdncpractica01;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author omar_
 */
public class ProductoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ProductoPrincipal
     */
    public ProductoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAgregarProducto = new javax.swing.JButton();
        jBModificarProducto = new javax.swing.JButton();
        jBEliminarProducto = new javax.swing.JButton();
        jBVerProductos = new javax.swing.JButton();
        jBVerProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido a gestion de");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos");

        jLabel3.setText("Omar Jazael Galindo Alducin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jBAgregarProducto.setText("Agregar Producto");
        jBAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProductoActionPerformed(evt);
            }
        });

        jBModificarProducto.setText("Modificar Producto");
        jBModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarProductoActionPerformed(evt);
            }
        });

        jBEliminarProducto.setText("Eliminar Producto");
        jBEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarProductoActionPerformed(evt);
            }
        });

        jBVerProductos.setText("Ver todos los productos");
        jBVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerProductosActionPerformed(evt);
            }
        });

        jBVerProducto.setText("Ver producto");
        jBVerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBModificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jBVerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jBAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerProductoActionPerformed
        String idStr = JOptionPane.showInputDialog("Ingrese el ID del producto a ver:");

        try {
            Long id = Long.parseLong(idStr);
            DAOProducto daoProducto = new DAOProducto();
            PojoProducto productoAVer = daoProducto.buscarById(id);

            if (productoAVer != null) {
                String mensaje = "Información del Producto:\n"
                + "ID: " + productoAVer.getId() + "\n"
                + "Descripción: " + productoAVer.getDescripcion() + "\n"
                + "Precio de Venta: " + productoAVer.getPrecioVenta() + "\n"
                + "Precio de Compra: " + productoAVer.getPrecioCompra();
                JOptionPane.showMessageDialog(this, mensaje, "Información del Producto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un producto con ese id", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar el id. Asegúrate de ingresa un id valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBVerProductoActionPerformed

    private void jBVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerProductosActionPerformed
        DAOProducto daoProducto = new DAOProducto();
        List<PojoProducto> listaProductos = daoProducto.buscarAll();

        if (!listaProductos.isEmpty()) {
            StringBuilder mensaje = new StringBuilder("Lista de productos:\n");

            for (PojoProducto producto : listaProductos) {
                mensaje.append("ID: ").append(producto.getId())
                .append(", Descripción: ").append(producto.getDescripcion())
                .append(", Precio de Venta: ").append(producto.getPrecioVenta())
                .append(", Precio de Compra: ").append(producto.getPrecioCompra())
                .append("\n");
            }
            JOptionPane.showMessageDialog(this, mensaje.toString(), "Lista de Productos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos para mostrar", "Lista de Productos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBVerProductosActionPerformed

    private void jBEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarProductoActionPerformed
        String idProducto = JOptionPane.showInputDialog("Ingrese el ID del producto a eliminar:");

        try {
            Long id = Long.parseLong(idProducto);
            DAOProducto daoProducto = new DAOProducto();
            PojoProducto productoAEliminar = daoProducto.buscarById(id);

            if (productoAEliminar != null) {
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Quieres eliminar el producto?", "Confirma tu desicion", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    if (daoProducto.eliminar(productoAEliminar)) {
                        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al eliminar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Se cancelo el eliminar");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un producto con ese id.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar el ID. Asegúrate de ingresar un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarProductoActionPerformed

    private void jBModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarProductoActionPerformed
        String idProducto = JOptionPane.showInputDialog("Ingresa el id del producto a modificar");
        try{
            Long id = Long.parseLong(idProducto);

            DAOProducto daoproducto = new DAOProducto();
            PojoProducto productoModificar = daoproducto.buscarById(id);
            if(productoModificar != null){
                String nuevaDesc = JOptionPane.showInputDialog("Ingresa la nueva descripcion");
                String nuevoPrecioVenta= JOptionPane.showInputDialog("Ingresa nuevo precio de venta");
                String nuevoPrecioCompra = JOptionPane.showInputDialog("Ingresa el nuevo precio de compra");

                double precioVenta = Double.parseDouble(nuevoPrecioVenta);
                double precioCompra = Double.parseDouble(nuevoPrecioCompra);

                productoModificar.setDescripcion(nuevaDesc);
                productoModificar.setPrecioVenta(precioVenta);
                productoModificar.setPrecioCompra(precioCompra);

                if(daoproducto.modificar(productoModificar)){
                    JOptionPane.showMessageDialog(this,"Producto modificado correctamente");
                }else{
                    JOptionPane.showMessageDialog(this,"Error al modificar el producto");
                }
            } else{
                JOptionPane.showMessageDialog(this,"No se encontro el producto con ese id");
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Error al ingresar el id, verifica que ingresaste bien el id");
        }
    }//GEN-LAST:event_jBModificarProductoActionPerformed

    private void jBAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProductoActionPerformed
        String descripcion = JOptionPane.showInputDialog("Ingrese la descripcion del producto");
        String precioVenta = JOptionPane.showInputDialog("Ingrese el precio de venta");
        String precioCompra = JOptionPane.showInputDialog("Ingrese el precio de compra");

        try{
            double precioVentaFinal = Double.parseDouble(precioVenta);
            double precioCompraFinal = Double.parseDouble(precioCompra);

            PojoProducto producto = new PojoProducto();
            producto.setDescripcion(descripcion);
            producto.setPrecioVenta(precioVentaFinal);
            producto.setPrecioCompra(precioCompraFinal);

            DAOProducto daoProducto = new DAOProducto();
            daoProducto.guardar(producto);
            JOptionPane.showMessageDialog(this, "Producto Agregado correctamente");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Producto Agregado correctamente");
        }
    }//GEN-LAST:event_jBAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarProducto;
    private javax.swing.JButton jBEliminarProducto;
    private javax.swing.JButton jBModificarProducto;
    private javax.swing.JButton jBVerProducto;
    private javax.swing.JButton jBVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
